// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer → Contacts*
 */
export interface FooterDocumentDataContactsItem {
  /**
   * Type field in *Footer → Contacts*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[].type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Phone" | "Email" | "Address">;

  /**
   * Label field in *Footer → Contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Footer → Socials*
 */
export interface FooterDocumentDataSocialsItem {
  /**
   * Icon field in *Footer → Socials*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"instagram" | "facebook" | "telegram" | "viber">;

  /**
   * Link field in *Footer → Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Contacts field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contacts: prismic.GroupField<Simplify<FooterDocumentDataContactsItem>>;

  /**
   * Socials field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<Simplify<FooterDocumentDataSocialsItem>>;

  /**
   * Copy Text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copy_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copy_text: prismic.KeyTextField;

  /**
   * Author Label field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.author_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_label: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | TestimonialsSlice
  | OffersSlice
  | BenefitsSlice
  | PartnersSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | VacanciesSlice
  | WorkingConditionsSlice
  | TechnologiesSlice
  | AboutSlice
  | AchievementsSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Home Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.home_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  home_link: prismic.LinkField;

  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Shop Link Label field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.shop_link_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shop_link_label: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Avatar field in *Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Highlighted Text field in *Testimonial*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.highlighted_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  highlighted_text: prismic.TitleField;

  /**
   * Main Text field in *Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.main_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_text: prismic.RichTextField;

  /**
   * Author field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Mark field in *Testimonial*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.mark
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  mark: prismic.SelectField<"1" | "2" | "3" | "4" | "5">;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialDocumentData>,
    "testimonial",
    Lang
  >;

/**
 * Item in *Vacancy → Requirements*
 */
export interface VacancyDocumentDataRequirementsItem {
  /**
   * Requirement field in *Vacancy → Requirements*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacancy.requirements[].requirement
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  requirement: prismic.RichTextField;
}

/**
 * Item in *Vacancy → Duties*
 */
export interface VacancyDocumentDataDutiesItem {
  /**
   * Duty field in *Vacancy → Duties*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacancy.duties[].duty
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  duty: prismic.RichTextField;
}

/**
 * Content for Vacancy documents
 */
interface VacancyDocumentData {
  /**
   * Title field in *Vacancy*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: vacancy.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Location field in *Vacancy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacancy.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Salary field in *Vacancy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacancy.salary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  salary: prismic.KeyTextField;

  /**
   * Time field in *Vacancy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacancy.time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  time: prismic.KeyTextField;

  /**
   * Requirements field in *Vacancy*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vacancy.requirements[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  requirements: prismic.GroupField<
    Simplify<VacancyDocumentDataRequirementsItem>
  >;

  /**
   * Duties field in *Vacancy*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vacancy.duties[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  duties: prismic.GroupField<Simplify<VacancyDocumentDataDutiesItem>>;
}

/**
 * Vacancy document from Prismic
 *
 * - **API ID**: `vacancy`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VacancyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<VacancyDocumentData>,
    "vacancy",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HomepageDocument
  | PageDocument
  | SettingsDocument
  | TestimonialDocument
  | VacancyDocument;

/**
 * Primary content in *About → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * First Paragraph field in *About → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.primary.first_paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  first_paragraph: prismic.RichTextField;

  /**
   * Second Paragraph field in *About → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.primary.second_paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_paragraph: prismic.RichTextField;

  /**
   * Third Paragraph field in *About → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.primary.third_paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  third_paragraph: prismic.RichTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Primary content in *Achievements → Items*
 */
export interface AchievementsSliceDefaultItem {
  /**
   * Value field in *Achievements → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: achievements.items[].value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value: prismic.KeyTextField;

  /**
   * Label field in *Achievements → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: achievements.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for Achievements Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AchievementsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<AchievementsSliceDefaultItem>
>;

/**
 * Slice variation for *Achievements*
 */
type AchievementsSliceVariation = AchievementsSliceDefault;

/**
 * Achievements Shared Slice
 *
 * - **API ID**: `achievements`
 * - **Description**: Achievements
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AchievementsSlice = prismic.SharedSlice<
  "achievements",
  AchievementsSliceVariation
>;

/**
 * Primary content in *Benefits → Primary*
 */
export interface BenefitsSliceDefaultPrimary {
  /**
   * Title field in *Benefits → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *Benefits → Items*
 */
export interface BenefitsSliceDefaultItem {
  /**
   * Title field in *Benefits → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Benefits → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Icon field in *Benefits → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    "Security" | "Reliability" | "Guarantees" | "Competence"
  >;
}

/**
 * Default variation for Benefits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BenefitsSliceDefaultPrimary>,
  Simplify<BenefitsSliceDefaultItem>
>;

/**
 * Slice variation for *Benefits*
 */
type BenefitsSliceVariation = BenefitsSliceDefault;

/**
 * Benefits Shared Slice
 *
 * - **API ID**: `benefits`
 * - **Description**: Benefits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSlice = prismic.SharedSlice<
  "benefits",
  BenefitsSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Titile field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titile
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titile: prismic.TitleField;

  /**
   * Subtitle field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceAlternativePrimary {
  /**
   * Titile field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titile
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titile: prismic.TitleField;

  /**
   * Subtitle field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Alternative variation for Hero Slice
 *
 * - **API ID**: `alternative`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceAlternative = prismic.SharedSliceVariation<
  "alternative",
  Simplify<HeroSliceAlternativePrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceAlternative;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Offers → Primary*
 */
export interface OffersSliceDefaultPrimary {
  /**
   * Title field in *Offers → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *Offers → Items*
 */
export interface OffersSliceDefaultItem {
  /**
   * Title field in *Offers → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Offers → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *Offers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *Offers → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Image field in *Offers → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: offers.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Offers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OffersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OffersSliceDefaultPrimary>,
  Simplify<OffersSliceDefaultItem>
>;

/**
 * Slice variation for *Offers*
 */
type OffersSliceVariation = OffersSliceDefault;

/**
 * Offers Shared Slice
 *
 * - **API ID**: `offers`
 * - **Description**: Offers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OffersSlice = prismic.SharedSlice<"offers", OffersSliceVariation>;

/**
 * Primary content in *Partners → Primary*
 */
export interface PartnersSliceDefaultPrimary {
  /**
   * Value field in *Partners → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.primary.value
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  value: prismic.RichTextField;

  /**
   * Label field in *Partners → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.primary.label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;
}

/**
 * Default variation for Partners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Partners*
 */
type PartnersSliceVariation = PartnersSliceDefault;

/**
 * Partners Shared Slice
 *
 * - **API ID**: `partners`
 * - **Description**: Partners
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSlice = prismic.SharedSlice<
  "partners",
  PartnersSliceVariation
>;

/**
 * Primary content in *Technologies → Primary*
 */
export interface TechnologiesSliceDefaultPrimary {
  /**
   * Title field in *Technologies → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: technologies.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *Technologies → Items*
 */
export interface TechnologiesSliceDefaultItem {
  /**
   * Title field in *Technologies → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: technologies.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Technologies → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: technologies.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Technologies → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: technologies.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Technologies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TechnologiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TechnologiesSliceDefaultPrimary>,
  Simplify<TechnologiesSliceDefaultItem>
>;

/**
 * Slice variation for *Technologies*
 */
type TechnologiesSliceVariation = TechnologiesSliceDefault;

/**
 * Technologies Shared Slice
 *
 * - **API ID**: `technologies`
 * - **Description**: Technologies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TechnologiesSlice = prismic.SharedSlice<
  "technologies",
  TechnologiesSliceVariation
>;

/**
 * Primary content in *Testimonials → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Title field in *Testimonials → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *Vacancies → Primary*
 */
export interface VacanciesSliceDefaultPrimary {
  /**
   * Title field in *Vacancies → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: vacancies.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *Vacancies → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vacancies.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for Vacancies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VacanciesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VacanciesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Vacancies*
 */
type VacanciesSliceVariation = VacanciesSliceDefault;

/**
 * Vacancies Shared Slice
 *
 * - **API ID**: `vacancies`
 * - **Description**: Vacancies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VacanciesSlice = prismic.SharedSlice<
  "vacancies",
  VacanciesSliceVariation
>;

/**
 * Primary content in *WorkingConditions → Items*
 */
export interface WorkingConditionsSliceDefaultItem {
  /**
   * Condition field in *WorkingConditions → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: working_conditions.items[].condition
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  condition: prismic.RichTextField;
}

/**
 * Default variation for WorkingConditions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkingConditionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<WorkingConditionsSliceDefaultItem>
>;

/**
 * Slice variation for *WorkingConditions*
 */
type WorkingConditionsSliceVariation = WorkingConditionsSliceDefault;

/**
 * WorkingConditions Shared Slice
 *
 * - **API ID**: `working_conditions`
 * - **Description**: WorkingConditions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkingConditionsSlice = prismic.SharedSlice<
  "working_conditions",
  WorkingConditionsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataContactsItem,
      FooterDocumentDataSocialsItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      TestimonialDocument,
      TestimonialDocumentData,
      VacancyDocument,
      VacancyDocumentData,
      VacancyDocumentDataRequirementsItem,
      VacancyDocumentDataDutiesItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      AchievementsSlice,
      AchievementsSliceDefaultItem,
      AchievementsSliceVariation,
      AchievementsSliceDefault,
      BenefitsSlice,
      BenefitsSliceDefaultPrimary,
      BenefitsSliceDefaultItem,
      BenefitsSliceVariation,
      BenefitsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceAlternativePrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceAlternative,
      OffersSlice,
      OffersSliceDefaultPrimary,
      OffersSliceDefaultItem,
      OffersSliceVariation,
      OffersSliceDefault,
      PartnersSlice,
      PartnersSliceDefaultPrimary,
      PartnersSliceVariation,
      PartnersSliceDefault,
      TechnologiesSlice,
      TechnologiesSliceDefaultPrimary,
      TechnologiesSliceDefaultItem,
      TechnologiesSliceVariation,
      TechnologiesSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      VacanciesSlice,
      VacanciesSliceDefaultPrimary,
      VacanciesSliceVariation,
      VacanciesSliceDefault,
      WorkingConditionsSlice,
      WorkingConditionsSliceDefaultItem,
      WorkingConditionsSliceVariation,
      WorkingConditionsSliceDefault,
    };
  }
}
