// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  benefits: dynamic(() => import("./Benefits")),
  hero: dynamic(() => import("./Hero")),
  offers: dynamic(() => import("./Offers")),
  partners: dynamic(() => import("./Partners")),
  testimonials: dynamic(() => import("./Testimonials")),
};
