// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  achievements: dynamic(() => import("./Achievements")),
  benefits: dynamic(() => import("./Benefits")),
  businesses: dynamic(() => import("./Businesses")),
  hero: dynamic(() => import("./Hero")),
  offers: dynamic(() => import("./Offers")),
  partners: dynamic(() => import("./Partners")),
  technologies: dynamic(() => import("./Technologies")),
  testimonials: dynamic(() => import("./Testimonials")),
  vacancies: dynamic(() => import("./Vacancies")),
  working_conditions: dynamic(() => import("./WorkingConditions")),
};
